---
- name: Space API Example
  hosts: all
  connection: httpapi
  gather_facts: no
  collections:
    - juniper.space

  tasks:
    - name: Get Addresses
      sd_address_info:
        # id: 458755
        # name: my_address
        # ip_address: 1.1.1.1
      register: output

    - debug:
        var: output
