---
- name: Space API Example
  hosts: all
  connection: httpapi
  gather_facts: no
  collections:
    - juniper.space

  tasks:
    - name: All devices
      space_queue:
        name: testq
        state: present
      register: output

    - debug:
        var: output
