---
- name: Space API Example
  hosts: all
  connection: httpapi
  gather_facts: no
  collections:
    - juniper.space

  tasks:
    - name: Get All NAT Rules for a Policy
      sd_nat_rule_info:
        policy_id: 458753
      register: output

    - debug:
        var: output
  
    - name: Get NAT Rule by ID
      sd_nat_rule_info:
        id: 458752
        policy_id: 458753
      register: output

    - debug:
        var: output
