---
- name: Space API Example
  hosts: all
  connection: httpapi
  gather_facts: no
  collections:
    - juniper.space

  tasks:
    - name: Get Addresses
      sd_address_info:
        # id: 196609
        # name: test_group2
        # ip_address: 192.168.1.1
      register: output

    - debug:
        var: output
